#!env php
<?php
require_once $_composer_autoload_path ?? dirname(__DIR__) . '/autoload.php';

use Gut\Gut;

if (empty($argv[1])) {
	exit('Usage: ' . __FILE__ . ' /full/path/to/target/file.php' . PHP_EOL);
}

$gut = new Gut();
$gut->generate($argv[1]);
